const TIPO_VALOR={
    DECIMAL:       'VAL_DECIMAL',
    CADENA:        'VAL_CADENA',
    IDENTIFICADOR: 'VAL_IDENTIFICADOR',
    ENTERO: 'VAL_ENTERO',
    BOOLEANO: 'VAL_BOOLEANO',
    CARACTER: 'VAL_CARACTER',
    VECTOR: 'VAL_VECTOR',
    VECTOR2D: 'VAL_VECTOR2D'
}

module.exports = TIPO_VALOR